-- GENERATION RUNS
create table generation_runs (
    db_id bigint generated by default as identity,
    run_id varchar(255) not null unique,
    generation_db_id bigint not null,
    attempt_number integer not null,
    state varchar(50) not null,
    reason varchar(50),
    message varchar(1000),
    start_time timestamp(6) with time zone,
    completion_time timestamp(6) with time zone,
    primary key (db_id)
);

-- ENHANCEMENT RUNS
create table enhancement_runs (
    db_id bigint generated by default as identity,
    run_id varchar(255) not null unique,
    enhancement_db_id bigint not null,
    attempt_number integer not null,
    state varchar(50) not null,
    reason varchar(50),
    message varchar(1000),
    start_time timestamp(6) with time zone,
    completion_time timestamp(6) with time zone,
    primary key (db_id)
);

-- Add new fields to existing tables
alter table requests add column child_generations_status varchar(50);
alter table generations add column child_enhancements_status varchar(50);
alter table generations add column latest_result varchar(50);
alter table enhancements add column latest_result varchar(50);

-- Foreign keys
alter table generation_runs
    add constraint FK_gen_run_gen
    foreign key (generation_db_id) references generations;

alter table enhancement_runs
    add constraint FK_enh_run_enh
    foreign key (enhancement_db_id) references enhancements;

-- Indexes for performance
create index idx_gen_runs_gen_id on generation_runs(generation_db_id);
create index idx_gen_runs_attempt on generation_runs(generation_db_id, attempt_number);
create index idx_enh_runs_enh_id on enhancement_runs(enhancement_db_id);
create index idx_enh_runs_attempt on enhancement_runs(enhancement_db_id, attempt_number);
create index idx_gen_runs_tsid on generation_runs(run_id);
create index idx_enh_runs_tsid on enhancement_runs(run_id);

-- Made with Bob
